version: 2.1
orbs:
  shipyard: shipyard/shipyard@3.6.1
jobs:
  ephemeral-e2e-tests:
    executor:
      name: shipyard/default
    steps:
      - checkout
      - shipyard/fetch-shipyard-env:
          app-name: 'shipyardmuuk'
      - run:
          command: |
            mkdir executor
            cd executor
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg
            sudo mkdir -p /etc/apt/keyrings
            NODE_MAJOR=20
            chmod a+r /usr/share/keyrings/nodesource.gpg
            echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
            sudo apt-get update
            sudo apt-get install nodejs -y
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
            sudo apt-get install gcc g++ make
            node -v
            sudo apt-get install -y unzip
            node -v
            printf '{ "key": "%s"}' $MUUKTEST_KEY > file.json
            cat file.json
            curl -H  "Content-Type: application/json" -X POST -d @file.json 'https://portal.muuktest.com:8081/generate_token_executer' -o "token.json"
            curl -X POST https://portal.muuktest.com:8081/api/v1/downloadpwfiles -k -d @file.json -H "Content-Type: application/json" -o ./config.zip
            unzip -o config.zip -d .
            TOKEN=$(jq --raw-output .token token.json)
            printf "Authorization: Bearer %s" $TOKEN > header.txt
            MUUK_USERID_TOKEN=$(jq --raw-output .userId token.json)
            printf '{"property": "tag", "value": ["TC44862"], "platform": "pw", "userId": "%s"}' $MUUK_USERID_TOKEN > body.json
            curl -X POST https://portal.muuktest.com:8081/download_byproperty -H @header.txt -d @body.json -H "Content-Type: application/json" -o ./test.zip
            [ -d "./test" ] && rm -r test
            unzip -o test.zip -d ./test
            ls -l
            BASE_TEST_URL=$SHIPYARD_ENVIRONMENT_URL'/?shipyard_token='$SHIPYARD_BYPASS_TOKEN
            echo $BASE_TEST_URL
            echo 'Update base url on test scripts' 
            sed -i '/let baseurl/a\  baseurl = `'$BASE_TEST_URL'`;' ./test/TestSteps_*.spec.ts
          name: Download MuukTest config and scripts
      - run:
          command: |
            cd executor
            npm install -D @playwright/test
            npx playwright install --with-deps chromium
            npm install axios
            npm install archiver
            npx playwright test --workers=3 --project=chromium
          name: Execute MuukTest on the ephemeral environment

workflows:
  use-my-orb:
    jobs:
      - ephemeral-e2e-tests
