version: 2.1
orbs:
  shipyard: shipyard/shipyard@3.6.1
jobs:
  ephemeral-e2e-tests:
    executor:
      name: shipyard/default
    steps:
      - checkout
      - shipyard/fetch-shipyard-env:
          app-name: 'shipyardmuuk'
      - run:
          command: |
            mkdir executor
            cd executor
            sudo apt-get update
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo apt-get install gcc g++ make
            node -v
            sudo apt-get install -y unzip
            node -v
            printf '{ "key": "%s"}' $MUUKTEST_KEY > file.json
            cat file.json
            curl -H  "Content-Type: application/json" -X POST -d @file.json 'https://portal.muuktest.com:8081/generate_token_executer' -o "token.json"
            curl -X POST https://portal.muuktest.com:8081/api/v1/downloadpwfiles -k -d @file.json -H "Content-Type: application/json" -o ./config.zip
            unzip -o config.zip -d .
            TOKEN=$(jq --raw-output .token token.json)
            printf "Authorization: Bearer %s" $TOKEN > header.txt
            MUUK_USERID_TOKEN=$(jq --raw-output .userId token.json)
            printf '{"property": "hashtag", "value": ["#uno"], "platform": "pw", "userId": "%s"}' $MUUK_USERID_TOKEN > body.json
            curl -X POST https://portal.muuktest.com:8081/download_byproperty -H @header.txt -d @body.json -H "Content-Type: application/json" -o ./test.zip
            [ -d "./test" ] && rm -r test
            unzip -o test.zip -d ./test
            ls -l
          name: Download MuukTest config and scripts
      - run:
          command: |
            cd executor
            npm install -D @playwright/test
            npx playwright install --with-deps chromium
            npm install axios
            npx playwright test --workers=4 --project=chromium
          name: Execute MuukTest on the ephemeral environment

workflows:
  use-my-orb:
    jobs:
      - ephemeral-e2e-tests
