version: 2.1
orbs:
  shipyard: shipyard/shipyard@3.6.1
jobs:
  ephemeral-e2e-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - shipyard/fetch-shipyard-env
      - run:
          command: |
            export BASE_URL=${SHIPYARD_ENVIRONMENT_URL}
            export BYPASS_TOKEN=${SHIPYARD_BYPASS_TOKEN}
            printenv
          name: Run the e2e tests on the ephemeral environment
workflows:
  use-my-orb:
    jobs:
      - ephemeral-e2e-tests