version: 2.1
orbs:
  shipyard: shipyard/shipyard@1
jobs:
  ephemeral-e2e-tests:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - shipyard/fetch-shipyard-env
      - run:
          command: |
            export BASE_URL=${SHIPYARD_ENVIRONMENT_URL}
            export BYPASS_TOKEN=${SHIPYARD_BYPASS_TOKEN}
            printenv
          name: Run the e2e tests on the ephemeral environment
workflows:
  execute:
    jobs:
      - ephemeral-e2e-tests