version: 2.1
orbs:
  shipyard: shipyard/shipyard@1
jobs:
  ephemeral-e2e-tests:
    docker:
    - environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - checkout
      - shipyard/fetch-shipyard-env
      - run:
          command: |
            export BASE_URL=${SHIPYARD_ENVIRONMENT_URL}
            export BYPASS_TOKEN=${SHIPYARD_BYPASS_TOKEN}
            printenv
          name: Run the e2e tests on the ephemeral environment
workflows:
  execute:
    jobs:
      - ephemeral-e2e-tests