on: [pull_request]

jobs:
  cypress-e2e-tests:
    runs-on: ubuntu-latest
    name: Collect the bypass token and URL for an authenticated ephemeral environment attached to this PR in order to run e2e tests on it.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Shipyard Tokens
        uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
            api-token: ${{ secrets.SHIPYARD_API_TOKEN }}
            app-name: 'shipyardmuuk'
            timeout-minutes: 30
      - name: Run the E2E tests against the ephemeral environment
        run: printenv
        shell: bash
        env:
            EPH_BASE_URL: $SHIPYARD_ENVIRONMENT_URL
            EPH_BYPASS_TOKEN: $SHIPYARD_BYPASS_TOKEN
